# **Primer avance PIA**


### Equipo: 2
### Grupo: 003
### Integrantes: 
- 	1726724 Tolentino Vargas Areli Fernanda
-	1816658 Martínez Martínez Arlette
-	1728777 Navarro Sosa Leslie Paola
-	1794335 Prado Porras Nadia Valeria
-	1812288 Reyes Joaquín Dayana Guadalupe

# 1) Título de la base de datos:
- [Life Expentancy (Who)](https://www.kaggle.com/kumarajarshi/life-expectancy-who)

# 2) Descripción de los datos

a) Tipo de datos.

La base de datos esta constituida por tipo númerico, excepto la columna País.

b) Descripción de las columnas

**País:** Lugar del cual se tomaron los datos.

**Anio:** Indica el año en que se recopilaron los datos, por país se tomaron en cuenta del año 2000 al 2015. 

**Estatus:** Indica si el país es desarrollado (tiene un alto nivel de vida) o está en desarrollo (economía en transición).

**Esperanza_de_Vida:** Esperanza de vida promedio al nacer, en años.

**Mortalidad de adultos:** Número de muertes de adultos de ambos sexos entre 15 y 60 años por cada 1000 habitantes.

**Mortalidad_infantil:** Número de muertes de niños por cada 1000 nacimientos vivos registrados, durante el primer año de vida.

**Alcohol:** Registro de consumo de alcohol medido en litros de alcohol puro per cápita por año.

**Porcentaje_de_gastos:** Gasto en salud como porcentaje del Producto Interno Bruto per cápita.

**Hepatitis_B:** Cobertura de inmunización por hepatitis B (HepB) en porcentaje de niños de 1 año.

**Sarampion:** Número de casos de sarampión notificados por cada 1000 habitantes.

**Indice_Masa_Corporal:** Índice promedio de masa corporal de toda la población.

**Muertes_niños_menores_a_5anios:** Número de muertes de niños menores de cinco años por cada 1000 habitantes.

**Poliomelitis:** Cobertura de inmunización contra la poliomielitis (Pol3) en porcentaje de niños de 1 año. 

**Gasto_total:** Gasto público general en salud como porcentaje del gasto público total.

**Difteria:** Cobertura de inmunización por difteria tétanos y tos ferina (DTP3) en porcentaje de niños de 1 año.
	
**VIH/SIDA:** Muertes por cada 1 000 nacidos vivos VIH/SIDA (0-4 años).

**PIB:** Producto Interno Bruto per cápita (en USD).

**Población:** Población total del país.

**Delgadez_1a19_anios:** Prevalencia de delgadez entre niños y adolescentes de 10 a 19 años en porcentaje

**Delgadez_5a9_anios:** Prevalencia de delgadez entre niños de 5 a 9 años en porcentaje.

**Composicion_de_los_ingresos_de_los_recursos:** Índice de Desarrollo Humano en términos de composición de ingresos de los recursos (índice que va de 0 a 1).

**Escolarización:** Número de años de escolarización.

# 3) Justificación del uso de datos

Las características que nos llamaron la atención al elegir la base de datos Life Expectancy Data es que la mayor parte de los valores son numéricos, por lo que podemos aplicar diferentes métodos estadísticos y probabilísticos para poder clasificar e interpretar información que obtendremos a partir de observar los datos, realizar modelos, estimaciones, predicciones y conclusiones acerca de los mismos.

El beneficio que nos aporta es practicar con una base de datos que es parecida a una utilizada en el ámbito laboral actuarial, lo que nos brinda una mejor noción de cómo trabajar con grandes cantidades de números, como extraer información importante de ellos y como utilizarla a nuestro favor para los propósitos específicos del área de interés profesional.

# 4) Objetivo final

La esperanza de vida es el número medio de años que se espera que siga viviendo una persona. Se puede calcular para diferentes edades y se realiza asumiendo que se mantienen las tasas de mortalidad por edad. Es una medida que resume la mortalidad de un país, permitiéndonos comparar por generaciones y analizar tendencias.

Su interpretación y significado nos puede aportar información clave sobre el nivel de desarrollo del estado de bienestar de un país, ya que tener una vida larga y saludable es el mejor indicativo del desarrollo social.

Su alargamiento es resultado, entre otras cuestiones, de las mejoras en alimentación, en sanidad, y sobre todo de una disminución de la mortalidad, pero también de otras cuestiones que conducen a las anteriores.

Por lo tanto, nuestro objetivo es conocer y comparar la situación y las características de la condición de vida de diferentes países del mundo en distintos años, determinando que factores de los presentados influyen realmente en la esperanza de vida, en qué medida lo hacen y cómo es que se relacionan.

# 5) Preguntas de interés
El conjunto de datos tiene como objetivo responder a las siguientes preguntas clave:

- ¿Afectan realmente a la esperanza de vida varios factores de predicción que se han elegido inicialmente? ¿Cuáles son las variables predictoras que realmente afectan la esperanza de vida?
- ¿La esperanza de vida tiene una correlación positiva o negativa con los hábitos alimenticios, el estilo de vida, el ejercicio, el tabaquismo, el consumo de alcohol, etc.

# 6) Parte de programación

#### a) Mostrar lo datos sin manipulación:
- Importar librerías y leer los datos.

In [2]:
import pandas as pd
import numpy as np
import json
import io
import csv
Datos= pd.read_csv('Life Expectancy Data.csv',na_values=[" "])
Datos

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8

- Ver caraterísticas del archivo

In [3]:
Datos = pd.read_csv('Life Expectancy Data.csv')
print("Numero de filas y columnas:",Datos.shape)
print("\nPrimeras 10 filas de datos:\n",Datos.head(10))
print("\nUltimas 10 filas de datos:\n",Datos.tail(10))

Numero de filas y columnas: (2938, 22)

Primeras 10 filas de datos:
        Country  Year      Status  Life expectancy   Adult Mortality  \
0  Afghanistan  2015  Developing              65.0            263.0
1  Afghanistan  2014  Developing              59.9            271.0
2  Afghanistan  2013  Developing              59.9            268.0
3  Afghanistan  2012  Developing              59.5            272.0
4  Afghanistan  2011  Developing              59.2            275.0
5  Afghanistan  2010  Developing              58.8            279.0
6  Afghanistan  2009  Developing              58.6            281.0
7  Afghanistan  2008  Developing              58.1            287.0
8  Afghanistan  2007  Developing              57.5            295.0
9  Afghanistan  2006  Developing              57.3            295.0

   infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   ...  \
0             62     0.01               71.279624         65.0      1154  ...
1             64     0.01               73.523582         62.0       492  ...
2             66     0.01               73.219243         64.0       430  ...
3             69     0.01               78.184215         67.0      2787  ...
4             71     0.01                7.097109         68.0      3013  ...
5             74     0.01               79.679367         66.0      1989  ...
6             77     0.01               56.762217         63.0      2861  ...
7             80     0.03               25.873925         64.0      1599  ...
8             82     0.02               10.910156         63.0      1141  ...
9             84     0.03               17.171518         64.0      1990  ...

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.0               8.16         65.0        0.1  584.259210  33736494.0
1   58.0               8.18         62.0        0.1  612.696514    327582.0
2   62.0               8.13         64.0        0.1  631.744976  31731688.0
3   67.0               8.52         67.0        0.1  669.959000   3696958.0
4   68.0               7.87         68.0        0.1   63.537231   2978599.0
5   66.0               9.20         66.0        0.1  553.328940   2883167.0
6   63.0               9.42         63.0        0.1  445.893298    284331.0
7   64.0               8.33         64.0        0.1  373.361116   2729431.0
8   63.0               6.73         63.0        0.1  369.835796  26616792.0
9   58.0               7.43         58.0        0.1  272.563770   2589345.0

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3
1                   17.5                 17.5
2                   17.7                 17.7
3                   17.9                 18.0
4                   18.2                 18.2
5                   18.4                 18.4
6                   18.6                 18.7
7                   18.8                 18.9
8                   19.0                 19.1
9                   19.2                 19.3

   Income composition of resources  Schooling
0                            0.479       10.1
1                            0.476       10.0
2                            0.470        9.9
3                            0.463        9.8
4                            0.454        9.5
5                            0.448        9.2
6                            0.434        8.9
7                            0.433        8.7
8                            0.415        8.4
9                            0.405        8.1

[10 rows x 22 columns]

Ultimas 10 filas de datos:
        Country  Year      Status  Life expectancy   Adult Mortality  \
2928  Zimbabwe  2009  Developing              50.0            587.0
2929  Zimbabwe  2008  Developing              48.2            632.0
2930  Zimbabwe  2007  Developing              46.6             67.0
2931  Zimbabwe  2006  Developing              45.4              7.0
2932  Zimbabwe  2005  Developing              44.6            717.0
2933  Zimbabwe  2004  Developing              44.3            723.0
2934  Zimbabwe  2003  Developing              44.5            715.0
2935  Zimbabwe  2002  Developing              44.8             73.0
2936  Zimbabwe  2001  Developing              45.3            686.0
2937  Zimbabwe  2000  Developing              46.0            665.0

      infant deaths  Alcohol  percentage expenditure  Hepatitis B  Measles   \
2928             30     4.64                1.040021         73.0       853
2929             30     3.56               20.843429         75.0         0
2930             29     3.88               29.814566         72.0       242
2931             28     4.57               34.262169         68.0       212
2932             28     4.14                8.717409         65.0       420
2933             27     4.36                0.000000         68.0        31
2934             26     4.06                0.000000          7.0       998
2935             25     4.43                0.000000         73.0       304
2936             25     1.72                0.000000         76.0       529
2937             24     1.68                0.000000         79.0      1483

      ...  Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  \
2928  ...   69.0               6.26         73.0       18.1   65.824121
2929  ...   75.0               4.96         75.0       20.5  325.678573
2930  ...   73.0               4.47         73.0       23.7  396.998217
2931  ...   71.0               5.12          7.0       26.8  414.796232
2932  ...   69.0               6.44         68.0       30.3  444.765750
2933  ...   67.0               7.13         65.0       33.6  454.366654
2934  ...    7.0               6.52         68.0       36.7  453.351155
2935  ...   73.0               6.53         71.0       39.8   57.348340
2936  ...   76.0               6.16         75.0       42.1  548.587312
2937  ...   78.0               7.10         78.0       43.5  547.358879

      Population   thinness  1-19 years   thinness 5-9 years  \
2928   1381599.0                    7.5                  7.4
2929  13558469.0                    7.8                  7.8
2930   1332999.0                    8.2                  8.2
2931  13124267.0                    8.6                  8.6
2932    129432.0                    9.0                  9.0
2933  12777511.0                    9.4                  9.4
2934  12633897.0                    9.8                  9.9
2935    125525.0                    1.2                  1.3
2936  12366165.0                    1.6                  1.7
2937  12222251.0                   11.0                 11.2

      Income composition of resources  Schooling
2928                            0.419        9.9
2929                            0.421        9.7
2930                            0.414        9.6
2931                            0.408        9.5
2932                            0.406        9.3
2933                            0.407        9.2
2934                            0.418        9.5
2935                            0.427       10.0
2936                            0.427        9.8
2937                            0.434        9.8

[10 rows x 22 columns]

- Renombrando las columnas.
 Renombramos las columnas ya que los títulos del archivo se encuentran en inglés, y para lograr un mayor entendimiento en el proceso las cambiamos a español.

In [4]:
print("\nNombres de las columnas",Datos.columns)
Datos.rename(columns = {'Country':'Pais','Year':'Anio','Status':'Estatus','Life expectancy ':'Esperanza_de_Vida','Adult Mortality':'Mortalidad_de_adultos','infant deaths':'Mortalidad_infantil','percentage expenditure':'Porcentaje_de_gastos','Hepatitis B':'Hepatitis_B' ,'Measles ':'Sarampion', 'Polio':'Poliomelitis', 'Total expenditure':'Gasto_total', 'Diphtheria ':'Difteria', 'Population':'Poblacion',' thinness  1-19 years':'Delgadez_1a19',' thinness 5-9 years':'Delgadez_5a9', 'Income composition of resources':'Composicion_de_los_ingresos_de_los_recursos', 'Schooling':'Escolarizacion','under-five deaths ':'muertes_niños','GDP':'PIB',' BMI ':'indice_masa_corporal'},inplace=True)
print("\nNuevos nombres de las columnas",Datos.columns)

Nombres de las columnas Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

Nuevos nombres de las columnas Index(['Pais', 'Anio', 'Estatus', 'Esperanza_de_Vida', 'Mortalidad_de_adultos',
       'Mortalidad_infantil', 'Alcohol', 'Porcentaje_de_gastos', 'Hepatitis_B',
       'Sarampion', 'indice_masa_corporal', 'muertes_niños', 'Poliomelitis',
       'Gasto_total', 'Difteria', ' HIV/AIDS', 'PIB', 'Poblacion',
       'Delgadez_1a19', 'Delgadez_5a9',
       'Composicion_de_los_ingresos_de_los_recursos', 'Escolarizacion'],
      dtype='object')

- Saber el tipo de dato de las columnas

In [5]:
print("\nTipo de dato que contiene cada columna:\n",Datos.dtypes)
print("\nEl tipo de dato de la columna Anio(año) es: ",Datos['Anio'].dtype)

Tipo de dato que contiene cada columna:
 Pais                                            object
Anio                                             int64
Estatus                                         object
Esperanza_de_Vida                              float64
Mortalidad_de_adultos                          float64
Mortalidad_infantil                              int64
Alcohol                                        float64
Porcentaje_de_gastos                           float64
Hepatitis_B                                    float64
Sarampion                                        int64
indice_masa_corporal                           float64
muertes_niños                                    int64
Poliomelitis                                   float64
Gasto_total                                    float64
Difteria                                       float64
 HIV/AIDS                                      float64
PIB                                            float64
Poblacion                                      float64
Delgadez_1a19                                  float64
Delgadez_5a9                                   float64
Composicion_de_los_ingresos_de_los_recursos    float64
Escolarizacion                                 float64
dtype: object

El tipo de dato de la columna Anio(año) es:  int64

- Cambiar el tipo de dato de una columna (con la finalidad de que todos los valores sean del mismo tipo), teniendo en cuenta el no perder información.

In [6]:
Datos['Anio']=Datos['Anio'].astype('float64')
print("\nEl nuevo tipo de dato de la columna Anio (año) es: ", Datos['Anio'].dtype)

El nuevo tipo de dato de la columna Anio (año) es:  float64

- Encontrar un valor dentro de un data frame dependiendo de los valores de otra columna

In [7]:
año_vs_pais= Datos.loc[Datos.Anio==2001].Pais
print("Paises considerados para obtención de datos del año 2001:\n",año_vs_pais)

Paises considerados para obtención de datos del año 2001:
 14                             Afghanistan
30                                 Albania
46                                 Algeria
62                                  Angola
78                     Antigua and Barbuda
                       ...
2872    Venezuela (Bolivarian Republic of)
2888                              Viet Nam
2904                                 Yemen
2920                                Zambia
2936                              Zimbabwe
Name: Pais, Length: 183, dtype: object

- Agrupación de datos por clases

In [8]:
print("\nClases de la columna Anio (año): ",Datos.Anio.unique())
año_2015=Datos[Datos['Anio']==2015.0]
año_2000=Datos[Datos['Anio']==2000.0]
año_2000
año_2015

Clases de la columna Anio (año):  [2015. 2014. 2013. 2012. 2011. 2010. 2009. 2008. 2007. 2006. 2005. 2004.
 2003. 2002. 2001. 2000.]

,Pais,Anio,Estatus,Esperanza_de_Vida,Mortalidad_de_adultos,Mortalidad_infantil,Alcohol,Porcentaje_de_gastos,Hepatitis_B,Sarampion,...,Poliomelitis,Gasto_total,Difteria,HIV/AIDS,PIB,Poblacion,Delgadez_1a19,Delgadez_5a9,Composicion_de_los_ingresos_de_los_recursos,Escolarizacion
0,Afghanistan,2015.0,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
16,Albania,2015.0,Developing,77.8,74.0,0,4.60,364.975229,99.0,0,...,99.0,6.00,99.0,0.1,3954.227830,28873.0,1.2,1.3,0.762,14.2
32,Algeria,2015.0,Developing,75.6,19.0,21,NaN,0.000000,95.0,63,...,95.0,NaN,95.0,0.1,4132.762920,39871528.0,6.0,5.8,0.743,14.4
48,Angola,2015.0,Developing,52.4,335.0,66,NaN,0.000000,64.0,118,...,7.0,NaN,64.0,1.9,3695.793748,2785935.0,8.3,8.2,0.531,11.4
64,Antigua and Barbuda,2015.0,Developing,76.4,13.0,0,NaN,0.000000,99.0,0,...,86.0,NaN,99.0,0.2,13566.954100,NaN,3.3,3.3,0.784,13.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2858,Venezuela (Bolivarian Republic of),2015.0,Developing,74.1,157.0,9,NaN,0.000000,87.0,0,...,87.0,NaN,87.0,0.1,NaN,NaN,1.6,1.5,0.769,14.3
2874,Viet Nam,2015.0,Developing,76.0,127.0,28,NaN,0.000000,97.0,256,...,97.0,NaN,97.0,0.1,NaN,NaN,14.2,14.5,0.678,12.6
2890,Yemen,2015.0,Developing,65.7,224.0,37,NaN,0.000000,69.0,468,...,63.0,NaN,69.0,0.1,NaN,NaN,13.6,13.4,0.499,9.0
2906,Zambia,2015.0,Developing,61.8,33.0,27,NaN,0.000000,9.0,9,...,9.0,NaN,9.0,4.1,1313.889646,161587.0,6.3,6.1,0.576,12.5
2922,Zimbabwe,2015.0,Developing,67.0,336.0,22,NaN,0.000000,87.0,0,...,88.0,NaN,87.0,6.2,118.693830,15777451.0,5.6,5.5,0.507,10.3

- Agrupamos los años 2000 y 2015 ya que son años de nuestro interés.

- Borraremos las columnas que no necesitamos para encontrar las respuestas a las preguntas de la sección 5.Solo queremos basarnos en las enfermedades.

In [11]:
df=Datos.drop(['Delgadez_5a9','Delgadez_1a19','Estatus','Porcentaje_de_gastos','Gasto_total','PIB','Composicion_de_los_ingresos_de_los_recursos','Escolarizacion'], axis = 1 )
df

,Pais,Anio,Esperanza_de_Vida,Mortalidad_de_adultos,Mortalidad_infantil,Alcohol,Hepatitis_B,Sarampion,indice_masa_corporal,muertes_niños,Poliomelitis,Difteria,HIV/AIDS,Poblacion
0,Afghanistan,2015.0,65.0,263.0,62,0.01,65.0,1154,19.1,83,6.0,65.0,0.1,33736494.0
1,Afghanistan,2014.0,59.9,271.0,64,0.01,62.0,492,18.6,86,58.0,62.0,0.1,327582.0
2,Afghanistan,2013.0,59.9,268.0,66,0.01,64.0,430,18.1,89,62.0,64.0,0.1,31731688.0
3,Afghanistan,2012.0,59.5,272.0,69,0.01,67.0,2787,17.6,93,67.0,67.0,0.1,3696958.0
4,Afghanistan,2011.0,59.2,275.0,71,0.01,68.0,3013,17.2,97,68.0,68.0,0.1,2978599.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004.0,44.3,723.0,27,4.36,68.0,31,27.1,42,67.0,65.0,33.6,12777511.0
2934,Zimbabwe,2003.0,44.5,715.0,26,4.06,7.0,998,26.7,41,7.0,68.0,36.7,12633897.0
2935,Zimbabwe,2002.0,44.8,73.0,25,4.43,73.0,304,26.3,40,73.0,71.0,39.8,125525.0
2936,Zimbabwe,2001.0,45.3,686.0,25,1.72,76.0,529,25.9,39,76.0,75.0,42.1,12366165.0
2937,Zimbabwe,2000.0,46.0,665.0,24,1.68,79.0,1483,25.5,39,78.0,78.0,43.5,12222251.0

- Revisar si hay datos nulos

In [12]:
print("\nExistencia de datos nulos por columna:\n",df.isnull().any())
print("\nCantidad de datos nulos por columna:\n",df.isnull().sum())
print("\nUltimas filas de datos:\n",df.tail(160))

Existencia de datos nulos por columna:
 Pais                     False
Anio                     False
Esperanza_de_Vida         True
Mortalidad_de_adultos     True
Mortalidad_infantil      False
Alcohol                   True
Hepatitis_B               True
Sarampion                False
indice_masa_corporal      True
muertes_niños            False
Poliomelitis              True
Difteria                  True
 HIV/AIDS                False
Poblacion                 True
dtype: bool

Cantidad de datos nulos por columna:
 Pais                       0
Anio                       0
Esperanza_de_Vida         10
Mortalidad_de_adultos     10
Mortalidad_infantil        0
Alcohol                  194
Hepatitis_B              553
Sarampion                  0
indice_masa_corporal      34
muertes_niños              0
Poliomelitis              19
Difteria                  19
 HIV/AIDS                  0
Poblacion                652
dtype: int64

Ultimas filas de datos:
                              Pais    Anio  Esperanza_de_Vida  \
2778  United Republic of Tanzania  2015.0               61.8
2779  United Republic of Tanzania  2014.0               67.0
2780  United Republic of Tanzania  2013.0               59.7
2781  United Republic of Tanzania  2012.0               58.6
2782  United Republic of Tanzania  2011.0               58.3
...                           ...     ...                ...
2933                     Zimbabwe  2004.0               44.3
2934                     Zimbabwe  2003.0               44.5
2935                     Zimbabwe  2002.0               44.8
2936                     Zimbabwe  2001.0               45.3
2937                     Zimbabwe  2000.0               46.0

      Mortalidad_de_adultos  Mortalidad_infantil  Alcohol  Hepatitis_B  \
2778                  279.0                   85      NaN         98.0
2779                   34.0                   86     0.01         97.0
2780                  323.0                   86     4.20         91.0
2781                  348.0                   87     3.98         92.0
2782                  348.0                   88     4.04          9.0
...                     ...                  ...      ...          ...
2933                  723.0                   27     4.36         68.0
2934                  715.0                   26     4.06          7.0
2935                   73.0                   25     4.43         73.0
2936                  686.0                   25     1.72         76.0
2937                  665.0                   24     1.68         79.0

      Sarampion  indice_masa_corporal  muertes_niños  Poliomelitis  Difteria  \
2778         30                  23.8            119          96.0      98.0
2779         88                  23.2            121          97.0      97.0
2780        185                  22.5            124          91.0      91.0
2781       1668                  21.9            126           9.0      92.0
2782       1622                  21.3            128          88.0       9.0
...         ...                   ...            ...           ...       ...
2933         31                  27.1             42          67.0      65.0
2934        998                  26.7             41           7.0      68.0
2935        304                  26.3             40          73.0      71.0
2936        529                  25.9             39          76.0      75.0
2937       1483                  25.5             39          78.0      78.0

       HIV/AIDS   Poblacion
2778        1.4         NaN
2779        1.4         NaN
2780        2.1         NaN
2781        2.4         NaN
2782        3.1         NaN
...         ...         ...
2933       33.6  12777511.0
2934       36.7  12633897.0
2935       39.8    125525.0
2936       42.1  12366165.0
2937       43.5  12222251.0

[160 rows x 14 columns]

Decidimos no borrar los datos nulos, si no llenarlos con 'NaN' así de esta manera no perderemos la información, ya que sí los elimina

In [13]:
df.to_csv('Esperanza_de_vidaLimpio.csv',index=False)